/**
 * Project Memory use cases.
 * CLI, tRPC, and MCP all share this layer.
 */

import fs from "node:fs";
import path from "node:path";
import type { ProjectMemory, ProjectMemoryCreate } from "syncpoint-core";
import * as repo from "../repositories.js";
import { isProjectLocal, getSyncpointDir } from "../db.js";

// ── Types ────────────────────────────────────────────

export interface ProjectMemoryAddInput extends ProjectMemoryCreate {
  /** If true, skip project-local check */
  global?: boolean;
}

export interface ProjectMemoryExportResult {
  path: string;
  count: number;
  content: string;
}

// ── Path guard ────────────────────────────────────────

export class ProjectMemoryPathError extends Error {
  constructor() {
    super(
      "No project-local .syncpoint/ found. Run `syncpoint init` first, " +
      "or use --global to write to the fallback location."
    );
    this.name = "ProjectMemoryPathError";
  }
}

function ensureProjectLocal(global?: boolean): void {
  if (global) return;
  if (!isProjectLocal()) throw new ProjectMemoryPathError();
}

// ── Use cases ────────────────────────────────────────

export function pmAdd(input: ProjectMemoryAddInput): ProjectMemory {
  ensureProjectLocal(input.global);
  return repo.createProjectMemory(input);
}

export function pmGet(id: string): ProjectMemory {
  return repo.getProjectMemory(id);
}

export function pmUpdate(id: string, fields: {
  title?: string;
  content?: string;
  tags?: string;
  confidence?: string;
  updatedBy?: string;
}): ProjectMemory {
  return repo.updateProjectMemory(id, fields);
}

export function pmApprove(id: string, updatedBy = ""): ProjectMemory {
  return repo.approveProjectMemory(id, updatedBy);
}

export function pmDeprecate(id: string, updatedBy = ""): ProjectMemory {
  return repo.deprecateProjectMemory(id, updatedBy);
}

export function pmList(filters?: {
  status?: string;
  category?: string;
  scope?: string;
  taskId?: string;
}): ProjectMemory[] {
  return repo.listProjectMemories(filters);
}

export function pmSearch(query: string): ProjectMemory[] {
  return repo.searchProjectMemories(query);
}

// ── Export ────────────────────────────────────────────

/**
 * Resolve the project-memory.md output path.
 * Priority: explicit arg > SYNCPOINT_MEMORY_PATH env > .syncpoint/project-memory.md
 */
function resolveMemoryPath(outputPath?: string): string {
  if (outputPath) return outputPath;
  if (process.env.SYNCPOINT_MEMORY_PATH) return process.env.SYNCPOINT_MEMORY_PATH;
  return path.join(getSyncpointDir(), "project-memory.md");
}

/**
 * Export approved project memories to .syncpoint/project-memory.md.
 * Returns the file path and content written.
 */
export function pmExport(outputPath?: string): ProjectMemoryExportResult {
  const approved = repo.listProjectMemories({ status: "approved" });
  const content = renderProjectMemoryMarkdown(approved);

  const target = resolveMemoryPath(outputPath);
  const dir = path.dirname(target);
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(target, content, "utf-8");

  return { path: target, count: approved.length, content };
}

function renderProjectMemoryMarkdown(memories: ProjectMemory[]): string {
  const lines: string[] = [];

  lines.push("# Project Memory");
  lines.push("");
  lines.push("> Auto-generated by SyncPoint. Do not edit manually.");
  lines.push(`> Generated: ${new Date().toISOString()}`);
  lines.push(`> Entries: ${memories.length} approved`);
  lines.push("");

  // Group by category
  const byCategory = new Map<string, ProjectMemory[]>();
  for (const m of memories) {
    const list = byCategory.get(m.category) ?? [];
    list.push(m);
    byCategory.set(m.category, list);
  }

  const categoryOrder = [
    "overview", "architecture", "decision", "convention",
    "risk", "gotcha", "glossary", "file-map", "integration",
  ];

  for (const cat of categoryOrder) {
    const items = byCategory.get(cat);
    if (!items || items.length === 0) continue;

    lines.push(`## ${cat.charAt(0).toUpperCase() + cat.slice(1)}`);
    lines.push("");

    for (const m of items) {
      lines.push(`### ${m.title}`);
      if (m.tags) lines.push(`> Tags: ${m.tags}`);
      if (m.confidence !== "medium") lines.push(`> Confidence: ${m.confidence}`);
      if (m.scope !== "project") lines.push(`> Scope: ${m.scope}`);
      lines.push("");
      lines.push(m.content);
      lines.push("");
    }
  }

  return lines.join("\n");
}
