/**
 * CLI demo commands.
 *
 * These commands create presentation-ready local data using the same
 * repository/application layers as the real CLI/MCP flows.
 */

import fs from "node:fs";
import path from "node:path";
import { Command } from "commander";
import {
  ContractStatus,
  ProjectMemoryCategory,
  ProjectMemoryConfidence,
  ProjectMemoryScope,
  ProjectMemorySourceType,
  ChecklistItemStatus,
} from "syncpoint-core";
import { getSyncpointDir, initSyncpointDir } from "syncpoint-server";
import * as repo from "syncpoint-server/repositories";
import {
  orchCreateSession,
  orchAssignRole,
  orchPlanTask,
  orchAcceptAssignment,
  orchStartAssignment,
  orchCompleteAssignment,
  orchRequestReview,
  orchStartReview,
  orchAdvanceSession,
  orchGetSessionStatus,
  rwCreateChecklistItem,
  rwUpdateChecklistItem,
  rwAddEvidence,
  rwEvaluateGate,
  rwApproveReview,
  rwPrepareReviewPacket,
  pmAdd,
  pmApprove,
  pmExport,
  rcClaim,
  rcRelease,
  stxCreate,
  stxApprove,
  stxResolve,
  sgAck,
  sgResolve,
  buildSnapshot,
  opCreate,
  opSubmit,
  opCheck,
  opApprove,
  opApply,
  rcDetectConflicts,
} from "syncpoint-server/application";
import { formatBlockedExplanation, formatStatusOutput } from "./formatter.js";
import type { Snapshot } from "./formatter.js";

interface DemoResult {
  ok: true;
  projectRoot: string;
  syncpointDir: string;
  reportPath: string;
  memoryPath: string;
  agents: {
    architectId: string;
    executorId: string;
    reviewerId: string;
  };
  taskId: string;
  contractId: string;
  sessionId: string;
  assignmentId: string;
  reviewRequestId: string;
  approvalRecordId: string;
  reviewDecisionId: string;
  gateStatus: string;
  sessionStatus: string;
}

function writeReport(outputPath: string, data: {
  projectRoot: string;
  syncpointDir: string;
  memoryPath: string;
  architect: ReturnType<typeof repo.createAgent>;
  executor: ReturnType<typeof repo.createAgent>;
  reviewer: ReturnType<typeof repo.createAgent>;
  task: ReturnType<typeof repo.createTask>;
  contract: ReturnType<typeof repo.getContract>;
  session: ReturnType<typeof orchCreateSession>["session"];
  assignmentId: string;
  reviewRequestId: string;
  checkpointId: string;
  snapshotId: string;
  gateStatus: string;
  approvalRecordId: string;
  reviewDecisionId: string;
  finalSessionStatus: ReturnType<typeof orchGetSessionStatus>;
}): void {
  const lines: string[] = [];

  lines.push("# SyncPoint MVP Demo");
  lines.push("");
  lines.push("> Generated by `syncpoint demo mvp`.");
  lines.push(`> Generated: ${new Date().toISOString()}`);
  lines.push("");
  lines.push("## One Sentence");
  lines.push("");
  lines.push("SyncPoint gives editor agents a shared local protocol for roles, task state, narrowed context, checkpoints, handoff, and evidence-based review.");
  lines.push("");
  lines.push("## Demo Flow");
  lines.push("");
  lines.push("```text");
  lines.push("Project Memory approved");
  lines.push("  -> Architect creates session");
  lines.push("  -> Executor receives task assignment");
  lines.push("  -> Executor checkpoints + writes context snapshot");
  lines.push("  -> Reviewer checks evidence");
  lines.push("  -> Approval gate passes");
  lines.push("  -> ReviewDecision approved");
  lines.push("  -> Session completed");
  lines.push("```");
  lines.push("");
  lines.push("## Agents");
  lines.push("");
  lines.push("| Role | Provider | Agent | ID |");
  lines.push("|---|---|---|---|");
  lines.push(`| Architect | ${data.architect.provider} | ${data.architect.name} | \`${data.architect.id}\` |`);
  lines.push(`| Executor | ${data.executor.provider} | ${data.executor.name} | \`${data.executor.id}\` |`);
  lines.push(`| Reviewer | ${data.reviewer.provider} | ${data.reviewer.name} | \`${data.reviewer.id}\` |`);
  lines.push("");
  lines.push("## Task");
  lines.push("");
  lines.push(`- Task: **${data.task.title}**`);
  lines.push(`- Task ID: \`${data.task.id}\``);
  lines.push(`- Contract ID: \`${data.contract.id}\``);
  lines.push(`- Contract status: \`${data.contract.status}\``);
  lines.push("");
  lines.push("## Synchronization Session");
  lines.push("");
  lines.push(`- Session ID: \`${data.session.id}\``);
  lines.push(`- Session status: \`${data.finalSessionStatus.session.status}\``);
  lines.push(`- Assignment ID: \`${data.assignmentId}\``);
  lines.push(`- Review request ID: \`${data.reviewRequestId}\``);
  lines.push("");
  lines.push("## Context Artifacts");
  lines.push("");
  lines.push(`- Checkpoint ID: \`${data.checkpointId}\``);
  lines.push(`- Context snapshot ID: \`${data.snapshotId}\``);
  lines.push(`- Project memory export: \`${data.memoryPath}\``);
  lines.push("");
  lines.push("## Review Result");
  lines.push("");
  lines.push(`- Approval gate: \`${data.gateStatus}\``);
  lines.push(`- Approval record ID: \`${data.approvalRecordId}\``);
  lines.push(`- Review decision ID: \`${data.reviewDecisionId}\``);
  lines.push("");
  lines.push("## Useful Commands");
  lines.push("");
  lines.push("```bash");
  lines.push(`syncpoint session status --session ${data.session.id}`);
  lines.push(`syncpoint review packet --review ${data.reviewRequestId}`);
  lines.push(`syncpoint review gate --review ${data.reviewRequestId}`);
  lines.push("```");
  lines.push("");
  lines.push("## Files");
  lines.push("");
  lines.push(`- Project root: \`${data.projectRoot}\``);
  lines.push(`- SyncPoint dir: \`${data.syncpointDir}\``);
  lines.push(`- Demo report: \`${outputPath}\``);
  lines.push("");

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, lines.join("\n"), "utf-8");
}

// ── Disaster Blocking Demo ─────────────────────────────

function runDisasterDemo(opts: { project: string; keep: boolean; json: boolean; stage: string }): void {
  const projectRoot = path.resolve(opts.project);
  fs.mkdirSync(projectRoot, { recursive: true });
  process.chdir(projectRoot);
  const syncpointDir = initSyncpointDir(projectRoot);

  const isJson = !!opts.json;
  const stage = opts.stage || "all";

  // ── Stage 1: Create agents ──
  const agentA = repo.createAgent({
    name: "agent-a-claude",
    provider: "claude-code",
    role: "backend",
  });
  const agentB = repo.createAgent({
    name: "agent-b-cursor",
    provider: "cursor",
    role: "backend",
  });
  const reviewer = repo.createAgent({
    name: "reviewer-agent",
    provider: "codex",
    role: "reviewer",
  });

  // ── Stage 2: Create session and task ──
  const task = repo.createTask({
    title: "Refactor shared authentication config",
    description: "Both agents need to modify the shared config file.",
  });
  repo.assignTask(task.id, agentA.id);

  const contractDraft = repo.createContract({
    taskId: task.id,
    title: "Shared config coordination",
    participants: [agentA.id, agentB.id, reviewer.id],
    scope: "Coordinate edits to src/shared-config.ts",
    responsibilities: ["Agent A handles auth logic", "Agent B handles token refresh", "Reviewer validates"],
    interfaceSpec: ["Both agents must claim files before editing."],
    fileBoundaries: ["src/shared-config.ts is the contended file."],
    dependencies: [],
    testPlan: "",
    risks: "Simultaneous edits to the same file without coordination.",
  });
  repo.updateContractStatus(contractDraft.id, ContractStatus.REVIEWING);
  repo.updateContractStatus(contractDraft.id, ContractStatus.APPROVED);

  const sessionResult = orchCreateSession({
    title: "Shared Config Coordination",
    description: "Two agents editing the same file — SyncPoint blocks unsafe continuation.",
    architectId: agentA.id,
    createdBy: "demo",
    relationshipMode: "peer-contract",
  });
  orchAssignRole({ sessionId: sessionResult.session.id, agentId: agentB.id, role: "executor" });
  orchAssignRole({ sessionId: sessionResult.session.id, agentId: reviewer.id, role: "reviewer" });

  const assignment = orchPlanTask({
    sessionId: sessionResult.session.id,
    taskId: task.id,
    assigneeAgentId: agentA.id,
    assignedBy: agentA.id,
    notes: "Agent A starts work on shared-config.ts",
  });
  orchAdvanceSession(sessionResult.session.id);
  orchAcceptAssignment(assignment.id);

  // ── Stage 3: Agent A claims the file (BEFORE starting work — required in peer-contract) ──
  const claimA = rcClaim({
    actorId: agentA.id,
    taskId: task.id,
    sessionId: sessionResult.session.id,
    resources: [{ type: "file", locator: "src/shared-config.ts", metadata: "" }],
    mode: "exclusive",
  });

  orchStartAssignment(assignment.id);

  // ── Stage 4: Agent A checkpoints ──
  const checkpoint = repo.createCheckpoint({
    taskId: task.id,
    agentId: agentA.id,
    summary: "Implemented auth session refresh logic in shared-config.ts",
    progress: "60%",
    currentUnderstanding: "Auth config needs token refresh handler.",
    changedFiles: ["src/shared-config.ts"],
    risks: "Another agent may edit the same file.",
    blockers: "",
    nextSteps: "Need review before Agent B can proceed.",
    needSync: true,
  });

  // Create sync transaction (checkpoint requires approval)
  const tx = stxCreate({
    sessionId: sessionResult.session.id,
    taskId: task.id,
    checkpointId: checkpoint.id,
    requestingAgentId: agentA.id,
    requiredApproverIds: [agentB.id],
  });

  // ── Stage 5: Agent B tries to claim the SAME file — CONFLICT ──
  const taskB = repo.createTask({
    title: "Add token refresh to shared config",
    description: "Agent B needs to add token refresh logic.",
  });
  repo.assignTask(taskB.id, agentB.id);

  const claimB = rcClaim({
    actorId: agentB.id,
    taskId: taskB.id,
    sessionId: sessionResult.session.id,
    resources: [{ type: "file", locator: "src/shared-config.ts", metadata: "" }],
    mode: "exclusive",
  });

  // ── Show blocked state ──
  const blockedSnapshot = buildSnapshot({ sessionId: sessionResult.session.id }) as Snapshot;

  if (isJson && stage === "blocked") {
    console.log(JSON.stringify(blockedSnapshot, null, 2));
    return;
  }

  if (!isJson) {
    console.log("");
    console.log(formatBlockedExplanation(blockedSnapshot));
    console.log("─".repeat(50));
    console.log(formatStatusOutput(blockedSnapshot));
  }

  if (stage === "blocked") {
    if (!isJson) {
      console.log("Demo paused at blocked state.");
      console.log(`Demo workspace: ${projectRoot}`);
      console.log("");
      console.log("To continue resolution:");
      console.log(`  syncpoint demo --project "${projectRoot}" --stage resolve`);
    }
    return;
  }

  // ── Stage 6: Resolution ──
  if (!isJson) {
    console.log("");
    console.log("═".repeat(50));
    console.log("Resolving blockers...");
    console.log("");
  }

  // Agent B approves the checkpoint transaction
  stxApprove(tx.tx.id, agentB.id, "Reviewed checkpoint, auth logic looks correct.");

  // Resolve the transaction (releases bound gate)
  stxResolve(tx.tx.id, "Checkpoint approved, ownership transfer agreed.");

  // Resolve the file conflict gate (created by claimB)
  if (claimB.gateId) {
    try { sgAck(claimB.gateId, agentA.id, "Agreed to transfer ownership"); } catch {}
    try { sgAck(claimB.gateId, agentB.id, "Ready to take over"); } catch {}
    try { sgResolve(claimB.gateId, "File ownership transferred from Agent A to Agent B"); } catch {}
  }
  rcRelease(claimA.claim.id);

  // ── Show resolved state ──
  const resolvedSnapshot = buildSnapshot({ sessionId: sessionResult.session.id }) as Snapshot;

  if (isJson) {
    console.log(JSON.stringify({
      stage: "resolved",
      blocked: blockedSnapshot,
      resolved: resolvedSnapshot,
    }, null, 2));
    return;
  }

  console.log("After resolution:");
  console.log("");
  console.log(formatStatusOutput(resolvedSnapshot));

  console.log("═".repeat(50));
  console.log("Demo complete.");
  console.log("");
  console.log("What happened:");
  console.log("  1. Agent A claimed src/shared-config.ts (exclusive)");
  console.log("  2. Agent A checkpointed — created a sync transaction requiring approval");
  console.log("  3. Agent B tried to claim the same file — BLOCKED by file conflict");
  console.log("  4. Agent B approved the checkpoint transaction");
  console.log("  5. File conflict gate resolved — ownership transferred");
  console.log("  6. Both agents can now continue safely");
  console.log("");
  console.log(`Demo workspace: ${projectRoot}`);
  if (!opts.keep) {
    console.log("  (use --keep to preserve the workspace for inspection)");
  }
}

// ── Resource-First Demo ───────────────────────────────

function runResourceDemo(opts: { project: string; json: boolean }): void {
  const projectRoot = path.resolve(opts.project);
  fs.mkdirSync(projectRoot, { recursive: true });
  process.chdir(projectRoot);
  initSyncpointDir(projectRoot);

  const isJson = !!opts.json;

  // ── Agents: a designer and an asset optimizer ──
  const designer = repo.createAgent({
    name: "design-agent",
    provider: "other",
    role: "frontend",
  });
  const optimizer = repo.createAgent({
    name: "asset-optimizer",
    provider: "other",
    role: "other",
  });

  // ── Task and session ──
  const task = repo.createTask({
    title: "Update hero banner for launch campaign",
    description: "Replace the hero banner and optimize all campaign images.",
  });
  repo.assignTask(task.id, designer.id);

  const sessionResult = orchCreateSession({
    title: "Launch Campaign Assets",
    description: "Coordinate binary asset changes between designer and optimizer.",
    architectId: designer.id,
    createdBy: "demo",
    relationshipMode: "peer-contract",
  });
  orchAssignRole({ sessionId: sessionResult.session.id, agentId: optimizer.id, role: "executor" });

  // ── Designer claims binary assets (type: "binary_asset", NOT "file") ──
  const claimDesigner = rcClaim({
    actorId: designer.id,
    taskId: task.id,
    sessionId: sessionResult.session.id,
    resources: [
      { type: "binary_asset", locator: "assets/hero-banner.png", metadata: "1920x600 PNG" },
      { type: "binary_asset", locator: "assets/campaign-logo.svg", metadata: "vector logo" },
    ],
    mode: "exclusive",
  });

  if (!isJson) {
    console.log("SyncPoint Resource-First Demo");
    console.log("═".repeat(50));
    console.log("");
    console.log("This demo uses type: \"binary_asset\" — not files, not code.");
    console.log("The same protocol primitives work for any resource type.");
    console.log("");
    console.log(`Designer claimed:`);
    console.log(`  [binary_asset] assets/hero-banner.png  (1920x600 PNG)`);
    console.log(`  [binary_asset] assets/campaign-logo.svg (vector logo)`);
    console.log("");
  }

  // ── Optimizer tries to claim the same banner — CONFLICT ──
  const taskOpt = repo.createTask({
    title: "Optimize hero banner for web performance",
    description: "Compress and resize hero-banner.png for web delivery.",
  });
  repo.assignTask(taskOpt.id, optimizer.id);

  const claimOptimizer = rcClaim({
    actorId: optimizer.id,
    taskId: taskOpt.id,
    sessionId: sessionResult.session.id,
    resources: [
      { type: "binary_asset", locator: "assets/hero-banner.png", metadata: "optimize to WebP" },
    ],
    mode: "exclusive",
  });

  if (!isJson && claimOptimizer.conflicts.length > 0) {
    console.log("Optimizer tried to claim assets/hero-banner.png — BLOCKED");
    console.log("");
    for (const c of claimOptimizer.conflicts) {
      console.log(`  [conflict] ${c.overlappingLocator}`);
      console.log(`    type: ${c.resourceType}`);
      console.log(`    ${c.claimA.actorId} ↔ ${c.claimB.actorId}`);
    }
    if (claimOptimizer.gateId) {
      console.log("");
      console.log(`  SyncGate created: ${claimOptimizer.gateId}`);
      console.log("  Both agents must sync before continuing.");
    }
  } else if (!isJson) {
    console.log("Optimizer claimed assets/hero-banner.png — no conflict (unexpected).");
  }

  // ── Resolve gate ──
  if (claimOptimizer.gateId) {
    try { sgAck(claimOptimizer.gateId, designer.id, "I'll finish the design first"); } catch {}
    try { sgAck(claimOptimizer.gateId, optimizer.id, "Waiting for final design"); } catch {}
    try { sgResolve(claimOptimizer.gateId, "Designer finishes first, then optimizer compresses"); } catch {}
  }

  if (!isJson) {
    console.log("");
    console.log("─".repeat(50));
    console.log("After resolution:");
    console.log("  Designer released claim → optimizer can now proceed.");
  }

  // Release optimizer's conflicting claim so the operation path is clean
  rcRelease(claimOptimizer.claim.id);

  // ══════════════════════════════════════════════════════
  // ── Part 2: Operation lifecycle (asset_edit) ──
  // ══════════════════════════════════════════════════════

  // Validators and resource matchers for binary_asset are provided by
  // syncpoint-plugin-generic-agent (auto-registered via _plugin-init.ts).
  // No inline registration needed.

  // Designer checkpoints with current asset state
  const designerCheckpoint = repo.createCheckpoint({
    taskId: task.id,
    agentId: designer.id,
    summary: "Completed new hero banner design for launch campaign",
    progress: "Design complete, ready for operation submission",
    changedFiles: ["assets/hero-banner.png"],
    currentUnderstanding: "hero-banner.png replaced with new campaign design",
    risks: "",
    blockers: "",
    nextSteps: "Submit asset_edit operation",
    needSync: false,
  });
  repo.createContextSnapshot({
    taskId: task.id,
    agentId: designer.id,
    checkpointId: designerCheckpoint.id,
    summary: "Replace hero banner for launch campaign",
    payload: {
      goal: "Replace hero banner for launch campaign",
      currentPhase: "implementation",
      confirmedDecisions: ["1920x600 PNG format, new branding"],
      workingResources: ["assets/hero-banner.png", "assets/campaign-logo.svg"],
      completedWork: "Hero banner design finalized",
      remainingWork: "Submit asset_edit operation",
      risks: [],
      blockers: [],
    },
  });

  // Designer creates and submits an asset_edit operation
  const operation = opCreate({
    type: "asset_edit",
    actorId: designer.id,
    taskId: task.id,
    sessionId: sessionResult.session.id,
    title: "Replace hero banner with new campaign design",
    summary: "New 1920x600 hero banner for launch campaign",
    targetResources: [
      { type: "binary_asset", locator: "assets/hero-banner.png", metadata: "1920x600 PNG" },
    ],
    payloadRef: "binary://assets/hero-banner-v2.png",
  });

  opSubmit(operation.id);
  const checkResult = opCheck(operation.id);
  opApprove(operation.id, designer.id, "Auto-approved after passing all checks");
  const applied = opApply(operation.id);

  // Release designer's claim after applying
  rcRelease(claimDesigner.claim.id);

  if (!isJson) {
    console.log("");
    console.log("═".repeat(50));
    console.log("Part 2: Operation lifecycle (type: \"asset_edit\")");
    console.log("═".repeat(50));
    console.log("");
    console.log(`Operation: ${operation.id}`);
    console.log(`  type: asset_edit`);
    console.log(`  target: [binary_asset] assets/hero-banner.png`);
    console.log(`  status flow: DRAFT → SUBMITTED → APPROVED → APPLIED`);
    console.log("");
    console.log("Validators executed:");
    const checks = checkResult.checkResult?.items ?? [];
    for (const item of checks) {
      console.log(`  [${item.passed ? "PASS" : "FAIL"}] ${item.check}: ${item.detail}`);
    }
    console.log("");
    console.log(`Final status: ${applied.status}`);
    console.log("");
    console.log("Key takeaway:");
    console.log("  SyncPoint's claim/conflict/gate/operation protocol works identically");
    console.log("  for binary_asset, db_table, api_endpoint — any resource type.");
    console.log("  No code-specific logic was involved.");
    console.log("");
    console.log(`Demo workspace: ${projectRoot}`);
  } else {
    console.log(JSON.stringify({
      designerClaim: claimDesigner,
      optimizerClaim: claimOptimizer,
      conflict: claimOptimizer.conflicts.length > 0,
      gateId: claimOptimizer.gateId,
      operation: {
        id: operation.id,
        type: operation.type,
        status: applied.status,
        targetResources: operation.targetResources,
        checks: checkResult.checkResult?.items ?? [],
      },
    }, null, 2));
  }
}

export function registerDemoCommands(program: Command): void {
  const demo = program
    .command("demo")
    .description("Run SyncPoint demos — shows how agents get blocked and unblocked")
    .action(() => {
      // Default: run the disaster (conflict) demo with defaults
      runDisasterDemo({
        project: path.join(process.cwd(), ".syncpoint", "demo-workspace"),
        keep: false,
        json: false,
        stage: "all",
      });
    });

  demo
    .command("conflict")
    .description("File conflict blocking demo — two agents claim the same file")
    .option(
      "--project <dir>",
      "Project directory for demo state",
      path.join(process.cwd(), ".syncpoint", "demo-workspace"),
    )
    .option("--keep", "Keep demo workspace for inspection", false)
    .option("--json", "Machine-readable JSON output")
    .option("--stage <stage>", "Run specific stage: blocked, resolve, all", "all")
    .action((opts) => {
      runDisasterDemo(opts);
    });

  demo
    .command("resource")
    .description("Resource-first demo — two agents claim the same binary asset, not code")
    .option(
      "--project <dir>",
      "Project directory for demo state",
      path.join(process.cwd(), ".syncpoint", "resource-demo-workspace"),
    )
    .option("--json", "Machine-readable JSON output")
    .action((opts) => {
      runResourceDemo(opts);
    });

  demo
    .command("mvp")
    .description("Create a full local MVP demo and write a showcase report")
    .option(
      "--project <dir>",
      "Project directory to initialize/use",
      path.join(process.cwd(), ".syncpoint", "mvp-demo-workspace"),
    )
    .option("--output <file>", "Markdown report path")
    .option("--json", "Output JSON")
    .action((opts) => {
      const projectRoot = path.resolve(opts.project);
      fs.mkdirSync(projectRoot, { recursive: true });
      process.chdir(projectRoot);

      const syncpointDir = initSyncpointDir(projectRoot);

      const architect = repo.createAgent({
        name: "mvp-architect",
        provider: "claude-code",
        role: "manager",
      });
      const executor = repo.createAgent({
        name: "mvp-executor",
        provider: "codex",
        role: "backend",
      });
      const reviewer = repo.createAgent({
        name: "mvp-reviewer",
        provider: "cursor",
        role: "reviewer",
      });

      const memories = [
        pmAdd({
          scope: ProjectMemoryScope.PROJECT,
          category: ProjectMemoryCategory.OVERVIEW,
          title: "SyncPoint MVP positioning",
          content: "SyncPoint is a local synchronization protocol layer for editor AI agents.",
          tags: ["mvp", "positioning"],
          sourceType: ProjectMemorySourceType.AGENT,
          sourceRef: "syncpoint-demo-mvp",
          confidence: ProjectMemoryConfidence.HIGH,
          taskId: null,
          createdBy: architect.id,
        }),
        pmAdd({
          scope: ProjectMemoryScope.PROJECT,
          category: ProjectMemoryCategory.ARCHITECTURE,
          title: "Layered protocol architecture",
          content: "Core defines protocol types; server owns application use cases; CLI and MCP are transport/adapters.",
          tags: ["architecture", "boundary"],
          sourceType: ProjectMemorySourceType.AGENT,
          sourceRef: "syncpoint-demo-mvp",
          confidence: ProjectMemoryConfidence.HIGH,
          taskId: null,
          createdBy: architect.id,
        }),
        pmAdd({
          scope: ProjectMemoryScope.PROJECT,
          category: ProjectMemoryCategory.DECISION,
          title: "Review requires evidence",
          content: "Reviewer approval must be backed by checklist state and at least one evidence record.",
          tags: ["review", "approval"],
          sourceType: ProjectMemorySourceType.AGENT,
          sourceRef: "syncpoint-demo-mvp",
          confidence: ProjectMemoryConfidence.HIGH,
          taskId: null,
          createdBy: reviewer.id,
        }),
      ];
      for (const memory of memories) pmApprove(memory.id, "demo");
      const memoryExport = pmExport(undefined, "demo");

      const task = repo.createTask({
        title: "MVP: evidence-backed multi-agent review",
        description: "Show Architect -> Executor -> Reviewer collaboration with checkpoint, snapshot, gate, and approval.",
      });
      repo.assignTask(task.id, executor.id);

      const contractDraft = repo.createContract({
        taskId: task.id,
        title: "MVP demo contract",
        participants: [architect.id, executor.id, reviewer.id],
        scope: "Implement and review a showcase-ready SyncPoint MVP flow.",
        responsibilities: ["Architect plans", "Executor implements", "Reviewer validates evidence"],
        interfaceSpec: ["CLI/MCP share application services and local SQLite state."],
        fileBoundaries: ["Demo data and generated report stay under the project .syncpoint directory."],
        dependencies: ["syncpoint-core", "syncpoint-server", "syncpoint-cli", "syncpoint-mcp"],
        testPlan: "Record build, typecheck, and test evidence before approval.",
        risks: "Approval without evidence is blocked by the review workflow gate.",
      });
      repo.updateContractStatus(contractDraft.id, ContractStatus.REVIEWING);
      const contract = repo.updateContractStatus(contractDraft.id, ContractStatus.APPROVED);

      const sessionResult = orchCreateSession({
        title: "MVP Demo Session",
        description: "Presentation-ready SyncPoint synchronization session.",
        architectId: architect.id,
        createdBy: "demo",
      });
      orchAssignRole({ sessionId: sessionResult.session.id, agentId: executor.id, role: "executor" });
      orchAssignRole({ sessionId: sessionResult.session.id, agentId: reviewer.id, role: "reviewer" });
      const assignment = orchPlanTask({
        sessionId: sessionResult.session.id,
        taskId: task.id,
        assigneeAgentId: executor.id,
        assignedBy: architect.id,
        notes: "Use checkpoint, snapshot, review evidence, and approval gate.",
      });
      orchAdvanceSession(sessionResult.session.id);
      orchAcceptAssignment(assignment.id);
      orchStartAssignment(assignment.id);

      const checkpoint = repo.createCheckpoint({
        taskId: task.id,
        agentId: executor.id,
        summary: "MVP workflow implemented for demo data.",
        progress: "100%",
        currentUnderstanding: "SyncPoint can coordinate synchronization boundaries and evidence-backed review.",
        changedFiles: ["packages/syncpoint-cli/src/commands/demo.ts", "docs/mvp-showcase.md"],
        risks: "Keep MVP focused on local protocol and avoid overpromising automatic runtime.",
        blockers: "",
        nextSteps: "Reviewer validates evidence and approval gate.",
        needSync: false,
      });

      const snapshot = repo.createContextSnapshot({
        taskId: task.id,
        agentId: executor.id,
        checkpointId: checkpoint.id,
        summary: "Demonstrate a complete SyncPoint collaboration loop.",
        payload: {
          goal: "Demonstrate a complete SyncPoint collaboration loop.",
          currentPhase: "review",
          confirmedDecisions: ["Use local SQLite state, CLI, MCP, and evidence-backed review."],
          interfaceContract: "Review approval requires checklist + evidence + no open changes.",
          workingResources: ["packages/syncpoint-cli/src/commands/demo.ts", "docs/review-workflow.md"],
          completedWork: "Session, task, contract, memory, checkpoint, snapshot, review evidence, and approval gate are created.",
          remainingWork: "Present the generated report.",
          risks: ["Demo is local-first and does not claim autonomous model scheduling."],
          blockers: [],
          nextSteps: ["Show mvp-demo.md and run session/review status commands."],
          resumePrompt: "Continue from the generated MVP demo report and inspect the review packet.",
        },
      });

      orchCompleteAssignment(assignment.id);
      orchAdvanceSession(sessionResult.session.id);

      const reviewRequest = orchRequestReview({
        sessionId: sessionResult.session.id,
        taskId: task.id,
        reviewerAgentId: reviewer.id,
        requestedBy: architect.id,
        scope: "Validate architecture boundary, context artifacts, and review evidence.",
      });
      orchStartReview(reviewRequest.id);

      const checklist = [
        rwCreateChecklistItem({ reviewRequestId: reviewRequest.id, title: "Project memory approved", required: true }),
        rwCreateChecklistItem({ reviewRequestId: reviewRequest.id, title: "Checkpoint and snapshot exist", required: true }),
        rwCreateChecklistItem({ reviewRequestId: reviewRequest.id, title: "Evidence-backed approval gate", required: true }),
      ];
      for (const item of checklist) {
        rwUpdateChecklistItem(item.id, ChecklistItemStatus.PASSED, {
          notes: "Verified in generated MVP flow.",
          updatedBy: reviewer.id,
        });
      }

      rwAddEvidence({
        reviewRequestId: reviewRequest.id,
        kind: "build",
        title: "pnpm build",
        content: "All workspace packages build successfully in the MVP validation flow.",
        metadataJson: JSON.stringify({ command: "pnpm build", source: "demo" }),
        createdBy: reviewer.id,
      });
      rwAddEvidence({
        reviewRequestId: reviewRequest.id,
        kind: "typecheck",
        title: "pnpm typecheck",
        content: "TypeScript project references typecheck successfully.",
        metadataJson: JSON.stringify({ command: "pnpm typecheck", source: "demo" }),
        createdBy: reviewer.id,
      });
      rwAddEvidence({
        reviewRequestId: reviewRequest.id,
        kind: "test",
        title: "pnpm test",
        content: "Full test suite is expected to pass before external presentation.",
        metadataJson: JSON.stringify({ command: "pnpm test", source: "demo" }),
        createdBy: reviewer.id,
      });

      const gate = rwEvaluateGate(reviewRequest.id);
      const approval = rwApproveReview({
        reviewRequestId: reviewRequest.id,
        summary: "MVP flow approved: checklist passed, evidence exists, and no open changes remain.",
        decidedBy: reviewer.id,
      });
      orchAdvanceSession(sessionResult.session.id);
      const finalSessionStatus = orchGetSessionStatus(sessionResult.session.id);
      const packet = rwPrepareReviewPacket(reviewRequest.id);

      const reportPath = path.resolve(opts.output ?? path.join(getSyncpointDir(), "mvp-demo.md"));
      writeReport(reportPath, {
        projectRoot,
        syncpointDir,
        memoryPath: memoryExport.path,
        architect,
        executor,
        reviewer,
        task,
        contract,
        session: sessionResult.session,
        assignmentId: assignment.id,
        reviewRequestId: reviewRequest.id,
        checkpointId: checkpoint.id,
        snapshotId: snapshot.id,
        gateStatus: gate.status,
        approvalRecordId: approval.approvalRecord.id,
        reviewDecisionId: approval.reviewDecision.id,
        finalSessionStatus,
      });

      const result: DemoResult = {
        ok: true,
        projectRoot,
        syncpointDir,
        reportPath,
        memoryPath: memoryExport.path,
        agents: {
          architectId: architect.id,
          executorId: executor.id,
          reviewerId: reviewer.id,
        },
        taskId: task.id,
        contractId: contract.id,
        sessionId: sessionResult.session.id,
        assignmentId: assignment.id,
        reviewRequestId: reviewRequest.id,
        approvalRecordId: approval.approvalRecord.id,
        reviewDecisionId: approval.reviewDecision.id,
        gateStatus: packet.gate.status,
        sessionStatus: finalSessionStatus.session.status,
      };

      if (opts.json) {
        console.log(JSON.stringify(result, null, 2));
        return;
      }

      console.log("SyncPoint MVP demo created.");
      console.log(`  Report:  ${reportPath}`);
      console.log(`  Memory:  ${memoryExport.path}`);
      console.log(`  Session: ${sessionResult.session.id} [${finalSessionStatus.session.status}]`);
      console.log(`  Review:  ${reviewRequest.id} gate=${packet.gate.status}`);
      console.log("");
      console.log("Show this report:");
      console.log(`  ${reportPath}`);
      console.log("");
      console.log("Useful commands:");
      console.log(`  syncpoint session status --session ${sessionResult.session.id}`);
      console.log(`  syncpoint review packet --review ${reviewRequest.id}`);
    });
}
