/**
 * CLI demo commands.
 *
 * These commands create presentation-ready local data using the same
 * repository/application layers as the real CLI/MCP flows.
 */

import fs from "node:fs";
import path from "node:path";
import { Command } from "commander";
import {
  ContractStatus,
  ProjectMemoryCategory,
  ProjectMemoryConfidence,
  ProjectMemoryScope,
  ProjectMemorySourceType,
  ChecklistItemStatus,
} from "syncpoint-core";
import { getSyncpointDir, initSyncpointDir } from "syncpoint-server";
import * as repo from "syncpoint-server/repositories";
import {
  orchCreateSession,
  orchAssignRole,
  orchPlanTask,
  orchAcceptAssignment,
  orchStartAssignment,
  orchCompleteAssignment,
  orchRequestReview,
  orchStartReview,
  orchAdvanceSession,
  orchGetSessionStatus,
  rwCreateChecklistItem,
  rwUpdateChecklistItem,
  rwAddEvidence,
  rwEvaluateGate,
  rwApproveReview,
  rwPrepareReviewPacket,
  pmAdd,
  pmApprove,
  pmExport,
} from "syncpoint-server/application";

interface DemoResult {
  ok: true;
  projectRoot: string;
  syncpointDir: string;
  reportPath: string;
  memoryPath: string;
  agents: {
    architectId: string;
    executorId: string;
    reviewerId: string;
  };
  taskId: string;
  contractId: string;
  sessionId: string;
  assignmentId: string;
  reviewRequestId: string;
  approvalRecordId: string;
  reviewDecisionId: string;
  gateStatus: string;
  sessionStatus: string;
}

function writeReport(outputPath: string, data: {
  projectRoot: string;
  syncpointDir: string;
  memoryPath: string;
  architect: ReturnType<typeof repo.createAgent>;
  executor: ReturnType<typeof repo.createAgent>;
  reviewer: ReturnType<typeof repo.createAgent>;
  task: ReturnType<typeof repo.createTask>;
  contract: ReturnType<typeof repo.getContract>;
  session: ReturnType<typeof orchCreateSession>["session"];
  assignmentId: string;
  reviewRequestId: string;
  checkpointId: string;
  capsuleId: string;
  gateStatus: string;
  approvalRecordId: string;
  reviewDecisionId: string;
  finalSessionStatus: ReturnType<typeof orchGetSessionStatus>;
}): void {
  const lines: string[] = [];

  lines.push("# SyncPoint MVP Demo");
  lines.push("");
  lines.push("> Generated by `syncpoint demo mvp`.");
  lines.push(`> Generated: ${new Date().toISOString()}`);
  lines.push("");
  lines.push("## One Sentence");
  lines.push("");
  lines.push("SyncPoint gives editor agents a shared local protocol for roles, task state, narrowed context, checkpoints, handoff, and evidence-based review.");
  lines.push("");
  lines.push("## Demo Flow");
  lines.push("");
  lines.push("```text");
  lines.push("Project Memory approved");
  lines.push("  -> Architect creates session");
  lines.push("  -> Executor receives task assignment");
  lines.push("  -> Executor checkpoints + writes context capsule");
  lines.push("  -> Reviewer checks evidence");
  lines.push("  -> Approval gate passes");
  lines.push("  -> ReviewDecision approved");
  lines.push("  -> Session completed");
  lines.push("```");
  lines.push("");
  lines.push("## Agents");
  lines.push("");
  lines.push("| Role | Provider | Agent | ID |");
  lines.push("|---|---|---|---|");
  lines.push(`| Architect | ${data.architect.provider} | ${data.architect.name} | \`${data.architect.id}\` |`);
  lines.push(`| Executor | ${data.executor.provider} | ${data.executor.name} | \`${data.executor.id}\` |`);
  lines.push(`| Reviewer | ${data.reviewer.provider} | ${data.reviewer.name} | \`${data.reviewer.id}\` |`);
  lines.push("");
  lines.push("## Task");
  lines.push("");
  lines.push(`- Task: **${data.task.title}**`);
  lines.push(`- Task ID: \`${data.task.id}\``);
  lines.push(`- Contract ID: \`${data.contract.id}\``);
  lines.push(`- Contract status: \`${data.contract.status}\``);
  lines.push("");
  lines.push("## Orchestration");
  lines.push("");
  lines.push(`- Session ID: \`${data.session.id}\``);
  lines.push(`- Session status: \`${data.finalSessionStatus.session.status}\``);
  lines.push(`- Assignment ID: \`${data.assignmentId}\``);
  lines.push(`- Review request ID: \`${data.reviewRequestId}\``);
  lines.push("");
  lines.push("## Context Artifacts");
  lines.push("");
  lines.push(`- Checkpoint ID: \`${data.checkpointId}\``);
  lines.push(`- Context capsule ID: \`${data.capsuleId}\``);
  lines.push(`- Project memory export: \`${data.memoryPath}\``);
  lines.push("");
  lines.push("## Review Result");
  lines.push("");
  lines.push(`- Approval gate: \`${data.gateStatus}\``);
  lines.push(`- Approval record ID: \`${data.approvalRecordId}\``);
  lines.push(`- Review decision ID: \`${data.reviewDecisionId}\``);
  lines.push("");
  lines.push("## Useful Commands");
  lines.push("");
  lines.push("```bash");
  lines.push(`syncpoint session status --session ${data.session.id}`);
  lines.push(`syncpoint review packet --review ${data.reviewRequestId}`);
  lines.push(`syncpoint review gate --review ${data.reviewRequestId}`);
  lines.push("```");
  lines.push("");
  lines.push("## Files");
  lines.push("");
  lines.push(`- Project root: \`${data.projectRoot}\``);
  lines.push(`- SyncPoint dir: \`${data.syncpointDir}\``);
  lines.push(`- Demo report: \`${outputPath}\``);
  lines.push("");

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, lines.join("\n"), "utf-8");
}

export function registerDemoCommands(program: Command): void {
  const demo = program
    .command("demo")
    .description("Create presentation-ready SyncPoint demos");

  demo
    .command("mvp")
    .description("Create a full local MVP demo and write a showcase report")
    .option(
      "--project <dir>",
      "Project directory to initialize/use",
      path.join(process.cwd(), ".syncpoint", "mvp-demo-workspace"),
    )
    .option("--output <file>", "Markdown report path")
    .option("--json", "Output JSON")
    .action((opts) => {
      const projectRoot = path.resolve(opts.project);
      fs.mkdirSync(projectRoot, { recursive: true });
      process.chdir(projectRoot);

      const syncpointDir = initSyncpointDir(projectRoot);

      const architect = repo.createAgent({
        name: "mvp-architect",
        provider: "claude-code",
        role: "manager",
      });
      const executor = repo.createAgent({
        name: "mvp-executor",
        provider: "codex",
        role: "backend",
      });
      const reviewer = repo.createAgent({
        name: "mvp-reviewer",
        provider: "cursor",
        role: "reviewer",
      });

      const memories = [
        pmAdd({
          scope: ProjectMemoryScope.PROJECT,
          category: ProjectMemoryCategory.OVERVIEW,
          title: "SyncPoint MVP positioning",
          content: "SyncPoint is a local multi-agent collaboration protocol layer for editor agents.",
          tags: "mvp,positioning",
          sourceType: ProjectMemorySourceType.AGENT,
          sourceRef: "syncpoint-demo-mvp",
          confidence: ProjectMemoryConfidence.HIGH,
          taskId: null,
          createdBy: architect.id,
        }),
        pmAdd({
          scope: ProjectMemoryScope.PROJECT,
          category: ProjectMemoryCategory.ARCHITECTURE,
          title: "Layered protocol architecture",
          content: "Core defines protocol types; server owns application use cases; CLI and MCP are transport/adapters.",
          tags: "architecture,boundary",
          sourceType: ProjectMemorySourceType.AGENT,
          sourceRef: "syncpoint-demo-mvp",
          confidence: ProjectMemoryConfidence.HIGH,
          taskId: null,
          createdBy: architect.id,
        }),
        pmAdd({
          scope: ProjectMemoryScope.PROJECT,
          category: ProjectMemoryCategory.DECISION,
          title: "Review requires evidence",
          content: "Reviewer approval must be backed by checklist state and at least one evidence record.",
          tags: "review,approval",
          sourceType: ProjectMemorySourceType.AGENT,
          sourceRef: "syncpoint-demo-mvp",
          confidence: ProjectMemoryConfidence.HIGH,
          taskId: null,
          createdBy: reviewer.id,
        }),
      ];
      for (const memory of memories) pmApprove(memory.id, "demo");
      const memoryExport = pmExport();

      const task = repo.createTask({
        title: "MVP: evidence-backed multi-agent review",
        description: "Show Architect -> Executor -> Reviewer collaboration with checkpoint, capsule, gate, and approval.",
      });
      repo.assignTask(task.id, executor.id);

      const contractDraft = repo.createContract({
        taskId: task.id,
        title: "MVP demo contract",
        participants: JSON.stringify([architect.id, executor.id, reviewer.id]),
        scope: "Implement and review a showcase-ready SyncPoint MVP flow.",
        responsibilities: "Architect plans, executor implements, reviewer validates evidence.",
        interfaceSpec: "CLI/MCP share application services and local SQLite state.",
        fileBoundaries: "Demo data and generated report stay under the project .syncpoint directory.",
        dependencies: "syncpoint-core, syncpoint-server, syncpoint-cli, syncpoint-mcp",
        testPlan: "Record build, typecheck, and test evidence before approval.",
        risks: "Approval without evidence is blocked by the review workflow gate.",
      });
      repo.updateContractStatus(contractDraft.id, ContractStatus.REVIEWING);
      const contract = repo.updateContractStatus(contractDraft.id, ContractStatus.APPROVED);

      const sessionResult = orchCreateSession({
        title: "MVP Demo Session",
        description: "Presentation-ready SyncPoint multi-agent collaboration session.",
        architectId: architect.id,
        createdBy: "demo",
      });
      orchAssignRole({ sessionId: sessionResult.session.id, agentId: executor.id, role: "executor" });
      orchAssignRole({ sessionId: sessionResult.session.id, agentId: reviewer.id, role: "reviewer" });
      const assignment = orchPlanTask({
        sessionId: sessionResult.session.id,
        taskId: task.id,
        assigneeAgentId: executor.id,
        assignedBy: architect.id,
        notes: "Use checkpoint, capsule, review evidence, and approval gate.",
      });
      orchAdvanceSession(sessionResult.session.id);
      orchAcceptAssignment(assignment.id);
      orchStartAssignment(assignment.id);

      const checkpoint = repo.createCheckpoint({
        taskId: task.id,
        agentId: executor.id,
        summary: "MVP workflow implemented for demo data.",
        progress: "100%",
        currentUnderstanding: "SyncPoint can coordinate role orchestration and evidence-backed review.",
        changedFiles: "packages/syncpoint-cli/src/commands/demo.ts, docs/mvp-showcase.md",
        risks: "Keep MVP focused on local protocol and avoid overpromising automatic runtime.",
        blockers: "",
        nextSteps: "Reviewer validates evidence and approval gate.",
        needSync: false,
      });

      const capsule = repo.createCapsule({
        taskId: task.id,
        agentId: executor.id,
        checkpointId: checkpoint.id,
        goal: "Demonstrate a complete SyncPoint collaboration loop.",
        currentPhase: "review",
        confirmedDecisions: "Use local SQLite state, CLI, MCP, and evidence-backed review.",
        interfaceContract: "Review approval requires checklist + evidence + no open changes.",
        workingFiles: "packages/syncpoint-cli/src/commands/demo.ts, docs/review-workflow.md",
        completedWork: "Session, task, contract, memory, checkpoint, capsule, review evidence, and approval gate are created.",
        remainingWork: "Present the generated report.",
        risks: "Demo is local-first and does not claim autonomous model scheduling.",
        blockers: "",
        nextSteps: "Show mvp-demo.md and run session/review status commands.",
        resumePrompt: "Continue from the generated MVP demo report and inspect the review packet.",
      });

      orchCompleteAssignment(assignment.id);
      orchAdvanceSession(sessionResult.session.id);

      const reviewRequest = orchRequestReview({
        sessionId: sessionResult.session.id,
        taskId: task.id,
        reviewerAgentId: reviewer.id,
        requestedBy: architect.id,
        scope: "Validate architecture boundary, context artifacts, and review evidence.",
      });
      orchStartReview(reviewRequest.id);

      const checklist = [
        rwCreateChecklistItem({ reviewRequestId: reviewRequest.id, title: "Project memory approved", required: true }),
        rwCreateChecklistItem({ reviewRequestId: reviewRequest.id, title: "Checkpoint and capsule exist", required: true }),
        rwCreateChecklistItem({ reviewRequestId: reviewRequest.id, title: "Evidence-backed approval gate", required: true }),
      ];
      for (const item of checklist) {
        rwUpdateChecklistItem(item.id, ChecklistItemStatus.PASSED, {
          notes: "Verified in generated MVP flow.",
          updatedBy: reviewer.id,
        });
      }

      rwAddEvidence({
        reviewRequestId: reviewRequest.id,
        kind: "build",
        title: "pnpm build",
        content: "All workspace packages build successfully in the MVP validation flow.",
        metadataJson: JSON.stringify({ command: "pnpm build", source: "demo" }),
        createdBy: reviewer.id,
      });
      rwAddEvidence({
        reviewRequestId: reviewRequest.id,
        kind: "typecheck",
        title: "pnpm typecheck",
        content: "TypeScript project references typecheck successfully.",
        metadataJson: JSON.stringify({ command: "pnpm typecheck", source: "demo" }),
        createdBy: reviewer.id,
      });
      rwAddEvidence({
        reviewRequestId: reviewRequest.id,
        kind: "test",
        title: "pnpm test",
        content: "Full test suite is expected to pass before external presentation.",
        metadataJson: JSON.stringify({ command: "pnpm test", source: "demo" }),
        createdBy: reviewer.id,
      });

      const gate = rwEvaluateGate(reviewRequest.id);
      const approval = rwApproveReview({
        reviewRequestId: reviewRequest.id,
        summary: "MVP flow approved: checklist passed, evidence exists, and no open changes remain.",
        decidedBy: reviewer.id,
      });
      orchAdvanceSession(sessionResult.session.id);
      const finalSessionStatus = orchGetSessionStatus(sessionResult.session.id);
      const packet = rwPrepareReviewPacket(reviewRequest.id);

      const reportPath = path.resolve(opts.output ?? path.join(getSyncpointDir(), "mvp-demo.md"));
      writeReport(reportPath, {
        projectRoot,
        syncpointDir,
        memoryPath: memoryExport.path,
        architect,
        executor,
        reviewer,
        task,
        contract,
        session: sessionResult.session,
        assignmentId: assignment.id,
        reviewRequestId: reviewRequest.id,
        checkpointId: checkpoint.id,
        capsuleId: capsule.id,
        gateStatus: gate.status,
        approvalRecordId: approval.approvalRecord.id,
        reviewDecisionId: approval.reviewDecision.id,
        finalSessionStatus,
      });

      const result: DemoResult = {
        ok: true,
        projectRoot,
        syncpointDir,
        reportPath,
        memoryPath: memoryExport.path,
        agents: {
          architectId: architect.id,
          executorId: executor.id,
          reviewerId: reviewer.id,
        },
        taskId: task.id,
        contractId: contract.id,
        sessionId: sessionResult.session.id,
        assignmentId: assignment.id,
        reviewRequestId: reviewRequest.id,
        approvalRecordId: approval.approvalRecord.id,
        reviewDecisionId: approval.reviewDecision.id,
        gateStatus: packet.gate.status,
        sessionStatus: finalSessionStatus.session.status,
      };

      if (opts.json) {
        console.log(JSON.stringify(result, null, 2));
        return;
      }

      console.log("SyncPoint MVP demo created.");
      console.log(`  Report:  ${reportPath}`);
      console.log(`  Memory:  ${memoryExport.path}`);
      console.log(`  Session: ${sessionResult.session.id} [${finalSessionStatus.session.status}]`);
      console.log(`  Review:  ${reviewRequest.id} gate=${packet.gate.status}`);
      console.log("");
      console.log("Show this report:");
      console.log(`  ${reportPath}`);
      console.log("");
      console.log("Useful commands:");
      console.log(`  syncpoint session status --session ${sessionResult.session.id}`);
      console.log(`  syncpoint review packet --review ${reviewRequest.id}`);
    });
}
