/**
 * Demo output — report generation and formatting for demo commands.
 */

import fs from "node:fs";
import path from "node:path";
import * as repo from "syncpoint-server/repositories";
import {
  orchCreateSession,
  orchGetSessionStatus,
} from "syncpoint-server/application";

export function writeDemoReport(outputPath: string, data: {
  projectRoot: string;
  syncpointDir: string;
  memoryPath: string;
  architect: ReturnType<typeof repo.createAgent>;
  executor: ReturnType<typeof repo.createAgent>;
  reviewer: ReturnType<typeof repo.createAgent>;
  task: ReturnType<typeof repo.createTask>;
  contract: ReturnType<typeof repo.getContract>;
  session: ReturnType<typeof orchCreateSession>["session"];
  assignmentId: string;
  reviewRequestId: string;
  checkpointId: string;
  snapshotId: string;
  gateStatus: string;
  approvalRecordId: string;
  reviewDecisionId: string;
  finalSessionStatus: ReturnType<typeof orchGetSessionStatus>;
}): void {
  const lines: string[] = [];

  lines.push("# SyncPoint MVP Demo");
  lines.push("");
  lines.push("> Generated by `syncpoint demo mvp`.");
  lines.push(`> Generated: ${new Date().toISOString()}`);
  lines.push("");
  lines.push("## One Sentence");
  lines.push("");
  lines.push("SyncPoint gives editor agents a shared local protocol for roles, task state, narrowed context, checkpoints, handoff, and evidence-based review.");
  lines.push("");
  lines.push("## Demo Flow");
  lines.push("");
  lines.push("```text");
  lines.push("Project Memory approved");
  lines.push("  -> Architect creates session");
  lines.push("  -> Executor receives task assignment");
  lines.push("  -> Executor checkpoints + writes context snapshot");
  lines.push("  -> Reviewer checks evidence");
  lines.push("  -> Approval gate passes");
  lines.push("  -> ReviewDecision approved");
  lines.push("  -> Session completed");
  lines.push("```");
  lines.push("");
  lines.push("## Agents");
  lines.push("");
  lines.push("| Role | Provider | Agent | ID |");
  lines.push("|---|---|---|---|");
  lines.push(`| Architect | ${data.architect.provider} | ${data.architect.name} | \`${data.architect.id}\` |`);
  lines.push(`| Executor | ${data.executor.provider} | ${data.executor.name} | \`${data.executor.id}\` |`);
  lines.push(`| Reviewer | ${data.reviewer.provider} | ${data.reviewer.name} | \`${data.reviewer.id}\` |`);
  lines.push("");
  lines.push("## Task");
  lines.push("");
  lines.push(`- Task: **${data.task.title}**`);
  lines.push(`- Task ID: \`${data.task.id}\``);
  lines.push(`- Contract ID: \`${data.contract.id}\``);
  lines.push(`- Contract status: \`${data.contract.status}\``);
  lines.push("");
  lines.push("## Synchronization Session");
  lines.push("");
  lines.push(`- Session ID: \`${data.session.id}\``);
  lines.push(`- Session status: \`${data.finalSessionStatus.session.status}\``);
  lines.push(`- Assignment ID: \`${data.assignmentId}\``);
  lines.push(`- Review request ID: \`${data.reviewRequestId}\``);
  lines.push("");
  lines.push("## Context Artifacts");
  lines.push("");
  lines.push(`- Checkpoint ID: \`${data.checkpointId}\``);
  lines.push(`- Context snapshot ID: \`${data.snapshotId}\``);
  lines.push(`- Project memory export: \`${data.memoryPath}\``);
  lines.push("");
  lines.push("## Review Result");
  lines.push("");
  lines.push(`- Approval gate: \`${data.gateStatus}\``);
  lines.push(`- Approval record ID: \`${data.approvalRecordId}\``);
  lines.push(`- Review decision ID: \`${data.reviewDecisionId}\``);
  lines.push("");
  lines.push("## Useful Commands");
  lines.push("");
  lines.push("```bash");
  lines.push(`syncpoint session status --session ${data.session.id}`);
  lines.push(`syncpoint review packet --review ${data.reviewRequestId}`);
  lines.push(`syncpoint review gate --review ${data.reviewRequestId}`);
  lines.push("```");
  lines.push("");
  lines.push("## Files");
  lines.push("");
  lines.push(`- Project root: \`${data.projectRoot}\``);
  lines.push(`- SyncPoint dir: \`${data.syncpointDir}\``);
  lines.push(`- Demo report: \`${outputPath}\``);
  lines.push("");

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, lines.join("\n"), "utf-8");
}
