/**
 * Kernel events — EventType enum, Event schema, and Event type.
 *
 * These are minimal coordination primitives used by every layer.
 * Physically hosted in kernel since Phase 3.
 */

import { z } from "zod";

// ── Helpers ──────────────────────────────────────────

const nanoid12 = z.string().min(1).max(24);
const isoDate = z.string().datetime({ offset: true });

// ── EventType ────────────────────────────────────────

export enum EventType {
  // Agent
  AGENT_REGISTERED = "AGENT_REGISTERED",
  AGENT_STATUS_CHANGED = "AGENT_STATUS_CHANGED",
  // Task
  TASK_CREATED = "TASK_CREATED",
  TASK_ASSIGNED = "TASK_ASSIGNED",
  TASK_STATUS_CHANGED = "TASK_STATUS_CHANGED",
  // Checkpoint
  CHECKPOINT_CREATED = "CHECKPOINT_CREATED",
  // Handoff
  HANDOFF_INITIATED = "HANDOFF_INITIATED",
  HANDOFF_ACCEPTED = "HANDOFF_ACCEPTED",
  HANDOFF_REJECTED = "HANDOFF_REJECTED",
  // Diary
  DIARY_ENTRY_CREATED = "DIARY_ENTRY_CREATED",
  // Contract
  PEER_KICKOFF = "PEER_KICKOFF",
  CONTRACT_DRAFTED = "CONTRACT_DRAFTED",
  CONTRACT_REVIEW_REQUESTED = "CONTRACT_REVIEW_REQUESTED",
  CONTRACT_APPROVED = "CONTRACT_APPROVED",
  CONTRACT_REJECTED = "CONTRACT_REJECTED",
  CONTRACT_UPDATED = "CONTRACT_UPDATED",
  WORK_STARTED = "WORK_STARTED",
  CHECKPOINT_SYNC = "CHECKPOINT_SYNC",
  CONFLICT_DETECTED = "CONFLICT_DETECTED",
  // Context Snapshot
  CONTEXT_SNAPSHOT_CREATED = "CONTEXT_SNAPSHOT_CREATED",
  // Project Memory
  PROJECT_MEMORY_CREATED = "PROJECT_MEMORY_CREATED",
  PROJECT_MEMORY_APPROVED = "PROJECT_MEMORY_APPROVED",
  PROJECT_MEMORY_DEPRECATED = "PROJECT_MEMORY_DEPRECATED",
  PROJECT_MEMORY_UPDATED = "PROJECT_MEMORY_UPDATED",
  // Orchestration (used by Wake Engine)
  SESSION_CREATED = "SESSION_CREATED",
  SESSION_ADVANCED = "SESSION_ADVANCED",
  SESSION_CANCELLED = "SESSION_CANCELLED",
  ROLE_ASSIGNED = "ROLE_ASSIGNED",
  ASSIGNMENT_CREATED = "ASSIGNMENT_CREATED",
  ASSIGNMENT_ACCEPTED = "ASSIGNMENT_ACCEPTED",
  ASSIGNMENT_STARTED = "ASSIGNMENT_STARTED",
  ASSIGNMENT_COMPLETED = "ASSIGNMENT_COMPLETED",
  REVIEW_REQUESTED = "REVIEW_REQUESTED",
  REVIEW_STARTED = "REVIEW_STARTED",
  REVIEW_DECIDED = "REVIEW_DECIDED",
  REVIEW_APPROVED = "REVIEW_APPROVED",
  REVIEW_BLOCKED = "REVIEW_BLOCKED",
  // Wake
  WAKE_CREATED = "WAKE_CREATED",
  WAKE_DISPATCHED = "WAKE_DISPATCHED",
  WAKE_DONE = "WAKE_DONE",
  WAKE_FAILED = "WAKE_FAILED",
  // ResourceClaim (generic)
  RESOURCE_CLAIMED = "RESOURCE_CLAIMED",
  RESOURCE_RELEASED = "RESOURCE_RELEASED",
  RESOURCE_CONFLICT_DETECTED = "RESOURCE_CONFLICT_DETECTED",
  FILE_CHANGED = "FILE_CHANGED",
  FILE_AUDIT_ALERT = "FILE_AUDIT_ALERT",
  FILE_POLLUTION_DETECTED = "FILE_POLLUTION_DETECTED",
  // SyncGate
  SYNC_GATE_CREATED = "SYNC_GATE_CREATED",
  SYNC_GATE_REQUESTED = "SYNC_GATE_REQUESTED",
  SYNC_GATE_ACKED = "SYNC_GATE_ACKED",
  SYNC_GATE_RESOLVED = "SYNC_GATE_RESOLVED",
  SYNC_GATE_CANCELLED = "SYNC_GATE_CANCELLED",
  // CheckpointReview
  SYNC_TX_CREATED = "SYNC_TX_CREATED",
  SYNC_TX_SUBMITTED = "SYNC_TX_SUBMITTED",
  SYNC_TX_APPROVED = "SYNC_TX_APPROVED",
  SYNC_TX_REJECTED = "SYNC_TX_REJECTED",
  SYNC_TX_RESOLVED = "SYNC_TX_RESOLVED",
  SYNC_TX_CANCELLED = "SYNC_TX_CANCELLED",
  // Operation (generic)
  OPERATION_CREATED = "OPERATION_CREATED",
  OPERATION_SUBMITTED = "OPERATION_SUBMITTED",
  OPERATION_CHECKED = "OPERATION_CHECKED",
  OPERATION_APPROVED = "OPERATION_APPROVED",
  OPERATION_REJECTED = "OPERATION_REJECTED",
  OPERATION_APPLIED = "OPERATION_APPLIED",
  OPERATION_CANCELLED = "OPERATION_CANCELLED",
  WRITE_PERMIT_REQUESTED = "WRITE_PERMIT_REQUESTED",
  WRITE_PERMIT_ISSUED = "WRITE_PERMIT_ISSUED",
  WRITE_PERMIT_DENIED = "WRITE_PERMIT_DENIED",
  WRITE_PERMIT_CONSUMED = "WRITE_PERMIT_CONSUMED",
  WRITE_PERMIT_REVOKED = "WRITE_PERMIT_REVOKED",
  WRITE_BLOCKED = "WRITE_BLOCKED",
  WRITE_STAGED = "WRITE_STAGED",
  WRITE_APPLIED = "WRITE_APPLIED",
  BACKING_STORE_BYPASS_DETECTED = "BACKING_STORE_BYPASS_DETECTED",
  // Agent Message
  AGENT_MESSAGE_SENT = "AGENT_MESSAGE_SENT",
  AGENT_MESSAGE_READ = "AGENT_MESSAGE_READ",
  AGENT_MESSAGE_REPLIED = "AGENT_MESSAGE_REPLIED",
  AGENT_MESSAGE_REMINDER = "AGENT_MESSAGE_REMINDER",
  AGENT_MESSAGE_ESCALATED = "AGENT_MESSAGE_ESCALATED",
  // Arbitration
  ARBITRATION_SESSION_STARTED = "ARBITRATION_SESSION_STARTED",
  ARBITRATION_VOTE_CAST = "ARBITRATION_VOTE_CAST",
  ARBITRATION_RESOLVED = "ARBITRATION_RESOLVED",
  // Guard
  GUARD_SESSION_CREATED = "GUARD_SESSION_CREATED",
  GUARD_ENGAGED = "GUARD_ENGAGED",
  GUARD_DISENGAGED = "GUARD_DISENGAGED",
  GUARD_VIOLATION = "GUARD_VIOLATION",
}

// ── Event Schema ─────────────────────────────────────

export const EventSchema = z.object({
  id: nanoid12,
  eventType: z.nativeEnum(EventType),
  entityType: z.enum(["agent", "task", "checkpoint", "handoff", "contract", "context_snapshot", "diary", "agent_message"]),
  entityId: nanoid12,
  detail: z.string().default(""),
  createdAt: isoDate,
});

export type Event = z.infer<typeof EventSchema>;
